In [1]:
import numpy as np
import pandas as pd
import os
import string
import re

pd.set_option('display.max_columns', None)

In [2]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.5)

In [3]:
from tqdm import tqdm

In [4]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/wsdm-cup-multilingual-chatbot-arena/sample_submission.csv
/kaggle/input/wsdm-cup-multilingual-chatbot-arena/train.parquet
/kaggle/input/wsdm-cup-multilingual-chatbot-arena/test.parquet
/kaggle/input/dom-data/dom_pickle
/kaggle/input/pickle-part-three/pixel_part_three
/kaggle/input/pickle-part-two/pixel_part_two

In [5]:
# df_sample = pd.read_csv("/kaggle/input/wsdm-cup-multilingual-chatbot-arena/sample_submission.csv")
df_train =pd.read_parquet("/kaggle/input/wsdm-cup-multilingual-chatbot-arena/train.parquet")
df_test = pd.read_parquet("/kaggle/input/wsdm-cup-multilingual-chatbot-arena/test.parquet")
df=df_train

### Code Detection

In [6]:
def contains_code(text):
    code_patterns = [
        r'```[\s\S]+?```',          
        r'`[^`]+`',          
        r'(?m)^(?: {4}|\t).+',
        r'\bdef\b|\bclass\b|\bimport\b|\breturn\b|\bprint\b|\bfor\b|\bwhile\b|\bif\b|\belse\b',
        r'<[a-zA-Z/][^>]*?>',          
    ]

    text = text.strip()

    for pattern in code_patterns:
        if re.search(pattern, text):
            if re.search(r'`[^`]+`', text):
                if not re.search(r'`[a-zA-Z0-9\s]+`', text):
                    return True
            else:
                return True
    return False

In [7]:
def first_text_categorization(row):
    prompt = row['prompt']
    response_a = row['response_a']
    response_b = row['response_b']
    
    prompt_bool = contains_code(prompt.lower())
    response_a_bool = contains_code(response_a.lower())
    response_b_bool = contains_code(response_b.lower())
    
    text_bool = prompt_bool or response_a_bool or response_b_bool
    return prompt_bool,response_a_bool,response_b_bool,text_bool

In [8]:
tqdm.pandas()
cs_data = list(df.progress_apply(first_text_categorization, axis=1))

100%|██████████| 48439/48439 [00:07<00:00, 6580.02it/s]

In [18]:
df['cs_data'] = cs_data
df['code_in_prompt']= df['cs_data'].apply(lambda x: x[0])
df['code_in_response_a']= df['cs_data'].apply(lambda x: x[1])
df['code_in_response_b']= df['cs_data'].apply(lambda x: x[2])
df['code']= df['cs_data'].apply(lambda x: x[3])
del(df['cs_data'])

In [19]:
def contains_code_xtreme(text):
    code_patterns = [
        r'[{}();=\[\]:<>]',
        r'#include\s*<.+>',        
        r'\bdef\s+\w+\s*\(.*\):',
        r'\bclass\s+\w+\s*\(?.*?\)?:',        
        r'```[a-zA-Z]*\n.*?```',
        r'^[ \t]*\w+.*\(.*\).*{',
    ]

    matches = sum(bool(re.search(pattern, text, re.MULTILINE)) for pattern in code_patterns)
    
    if matches >= 2:
        return True

    if re.search(r'```.*?```|`[^`]+`', text, re.MULTILINE):
        return True

    lines = text.split('\n')
    symbol_count_threshold = 5
    for line in lines:
        symbols = re.findall(r'[{}();=\[\]:<>]', line)
        if len(symbols) >= symbol_count_threshold:
            return True

    return False

In [20]:
def main_contains_code_xtreme(row):
    prompt = row['prompt']
    response_a = row['response_a']
    response_b = row['response_b']

    prompt_bool = row['code_in_prompt']
    response_a_bool = row['code_in_response_a']
    response_b_bool = row['code_in_response_b']
    text_bool = row['code']
    
    if text_bool==False:
        return False,False,False,False

    if prompt_bool:
        prompt_bool = contains_code_xtreme(prompt)
    if response_a_bool:
        response_a_bool = contains_code_xtreme(response_a)
    if response_b_bool:
        response_b_bool = contains_code_xtreme(response_b)
    
    text_bool = prompt_bool or response_a_bool or response_b_bool
    return prompt_bool,response_a_bool,response_b_bool,text_bool

In [21]:
tqdm.pandas()
x_cs_data = list(df.progress_apply(main_contains_code_xtreme, axis=1))

100%|██████████| 48439/48439 [00:12<00:00, 3968.05it/s]

In [22]:
df['x_cs_data'] = x_cs_data
df['code_in_prompt']= df['x_cs_data'].apply(lambda x: x[0])
df['code_in_response_a']= df['x_cs_data'].apply(lambda x: x[1])
df['code_in_response_b']= df['x_cs_data'].apply(lambda x: x[2])
df['code']= df['x_cs_data'].apply(lambda x: x[3])
del(df['x_cs_data'])

In [23]:
len(df[df['code']==True]) , len(df[df['code_in_prompt']==True]) , len(df[df['code_in_response_a']==True]) , len(df[df['code_in_response_b']==True])

(12082, 3993, 6154, 6057)

### Code Language detection for Code = True

In [24]:
import re

def detect_code_language_details(text):

    web_dev_pattern = re.compile(
    r'(?i)(?:'
    r'\{[^{}]*?\b[a-zA-Z-]+\s*:\s*[^;{}]+;\s*\}|'  
    r'<style\b[^>]*>[^<]*?\{[^{}]*?\b[a-zA-Z-]+\s*:\s*[^;{}]+;\s*\}[^<]*<\/style>|'
    r'\b(function|var|let|const|=>|return|if|else|for|while|class)\b|'  
    r'<[a-zA-Z!\/][^>]*>'
    r')'
) 
    python_pattern = re.compile(r"\b(def|class|import|from|try|except|with|open|input|print|len|map|filter|zip|lambda|enumerate|range|dict|list|set|tuple|pandas|numpy|matplotlib|seaborn|scikit-learn|tensorflow|keras|torch|DataFrame|Series|read_csv|read_excel|head|tail|describe|groupby|merge|concat|plot|scatter|hist|bar|boxplot|mean|median|std|min|max|sum|apply|transform|pivot_table|correlation|train_test_split|fit|predict|accuracy_score|confusion_matrix|classification_report|roc_curve|auc)\b")
    java_pattern = re.compile(r"\b(public|private|protected|class|void|String|new|try|catch)\b")
    cpp_pattern = re.compile(r"\b(int|float|double|char|class|#include)\b")
    comprehensive_pattern = re.compile(r"\b(lambda|print|System\.out\.println|cout|cin|alert)\b")

    web_dev_matches = web_dev_pattern.findall(text)
    python_matches = python_pattern.findall(text)
    java_matches = java_pattern.findall(text)
    cpp_matches = cpp_pattern.findall(text)
    comprehensive_matches = comprehensive_pattern.findall(text)

    filtered_python_matches = [m for m in python_matches if m not in {"if", "return", "for", "while"}]
    filtered_java_matches = [m for m in java_matches if m not in {"if", "return", "for", "while"}]
    filtered_cpp_matches = [m for m in cpp_matches if m not in {"if", "return", "for", "while"}]

    lang_list = []
    if len(list(set(web_dev_matches)))>0:
        lang_list.append(1)
    else:
        lang_list.append(0)
        
    if len(list(set(python_matches)))>0 or len(list(set(java_matches)))>0 or len(list(set(cpp_matches)))>0:
        lang_list.append(1)
    else:
        lang_list.append(0)
        
    if len(list(set(comprehensive_matches)))>0:
        lang_list.append(1)
    else:
        lang_list.append(0)

    return lang_list

In [25]:
# "Web-dev", ["Python" | "Java" | "C++"], "Comprehensive"

def detect_code_language(row):
    if row['code']==True:
        code_languages_in_prompt = detect_code_language_details(row['prompt'])
        code_languages_in_response_a =  detect_code_language_details(row['response_a'])
        code_languages_in_response_b =  detect_code_language_details(row['response_b'])
        return [code_languages_in_prompt,code_languages_in_response_a,code_languages_in_response_b]
    else:
        code_languages_in_prompt=[0,0,0]
        code_languages_in_response_a=[0,0,0]
        code_languages_in_response_b=[0,0,0]
        return [code_languages_in_prompt,code_languages_in_response_a,code_languages_in_response_b]

In [26]:
df[["code_languages_in_prompt", "code_languages_in_response_a", "code_languages_in_response_b"]] = df.apply(detect_code_language, axis=1, result_type="expand")

### Light Preprocessing for prompt - removing punctuations

In [27]:
def clean_for_segmentation(row):    
    text = row['prompt']
    characters_to_remove = r"[-.,\n'\":!?]"
    cleaned_text = re.sub(characters_to_remove, "", text)
    final_text = re.sub(r"\s+", " ", cleaned_text).strip()
    return final_text

In [28]:
df['ft_prompt'] = df.apply(clean_for_segmentation,axis=1)

### Segmentation

In [29]:
df["prompt_len"] = df['ft_prompt'].apply(lambda x: len(x.split(' ')))

In [30]:
def segmentation(row):
    sentences=[]
    prompt_len = row['prompt_len']
    prompt = row['ft_prompt']
    prompt_arr = prompt.split(' ')
    segment = 6
    if prompt_len<6:
        text = " ".join(prompt_arr[0:prompt_len])
        sentences.append(text)
    else:
        for i in range(0,prompt_len,segment):
            if i+(2*segment)>prompt_len:
                text = " ".join(prompt_arr[i:prompt_len])
                sentences.append(text)
                break
            else:    
                text = " ".join(prompt_arr[i:i+segment])
                sentences.append(text)
    return sentences

In [31]:
df['prompt_segements'] = df.apply(segmentation,axis=1)

### Dominating language

In [32]:
!pip install langcodes
!pip install langdetect

Requirement already satisfied: langcodes in /usr/local/lib/python3.10/dist-packages (3.4.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes) (1.2.0)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from marisa-trie>=0.7.7->language-data>=1.2->langcodes) (71.0.4)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 13.8 MB/s eta 0:00:0000:010:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect) (1.16.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993221 sha256=327bd335bc4d560e90db87879068f1efc72cd6da9eef0434f475d7100a9982f6
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [33]:
from nltk.corpus import stopwords
import nltk 

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [34]:
import langcodes
from langdetect import detect, detect_langs

In [35]:
def lang_detection_prompt(row):
    sentences = row['prompt_segements']
    extra_stopwords = []
    language_dict = {}
    language_frequency = {}
    language_weight = {}
    total= 0
    filtered_prompt = ''
    
    for sentence in sentences:
        try:
            detected_code = detect(sentence) 
            detected_language = langcodes.Language.get(detected_code).display_name()

            if detected_language in language_frequency:
                language_frequency[detected_language] += 1
            else:
                language_frequency[detected_language] = 1

            if (detected_language is None) or (detected_language ==''):
                detected_language = 'english'
            
        except Exception as e:
            break
    
    for key in list(language_frequency.keys()):
        total = total+ language_frequency[key]

    for key in list(language_frequency.keys()):
        language_weight[key]= language_frequency[key]/total

    # return [filtered_prompt,language_frequency,language_weight]
    return [language_frequency,language_weight]

In [36]:
tqdm.pandas()
ls_prompt = list(df.progress_apply(lang_detection_prompt, axis=1))

100%|██████████| 48439/48439 [1:22:21<00:00,  9.80it/s]

In [37]:
df['prompt_meta'] = ls_prompt
df['prompt_counter']= df['prompt_meta'].apply(lambda x: x[0])
df['prompt_weight']= df['prompt_meta'].apply(lambda x: x[1])
del(df['prompt_meta'])

In [38]:
df.head()

,id,prompt,response_a,response_b,winner,model_a,model_b,language,code_in_prompt,code_in_response_a,code_in_response_b,code,code_languages_in_prompt,code_languages_in_response_a,code_languages_in_response_b,ft_prompt,prompt_len,prompt_segements,prompt_counter,prompt_weight
0,00007cff95d7f7974642a785aca248b0f26e60d3312fac...,vieš po Slovensky?,"Áno, hovorím po slovensky. Ako vám môžem pomôcť?","Áno, veď som tu! Môžem ti pomôcť s otázkami al...",model_a,o1-preview,reka-core-20240904,Slovak,False,False,False,False,"[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",vieš po Slovensky,3,[vieš po Slovensky],{'Slovak': 1},{'Slovak': 1.0}
1,00010ed04b536f56ebe43eef1100c13906abea12bf9855...,You will be given a piece of news. Analyze it ...,Let's break down the news and analyze it accor...,"```json\n{\n ""contains_orgs"": true,\n ""orgs""...",model_a,gemma-2-27b-it,gemini-1.5-flash-002,Russian,False,True,True,True,"[1, 1, 0]","[1, 1, 0]","[0, 0, 0]",You will be given a piece of news Analyze it a...,357,"[You will be given a piece, of news Analyze it...","{'English': 20, 'Russian': 39}","{'English': 0.3389830508474576, 'Russian': 0.6..."
2,0003800d510e38803efba5ceaec122bc66408fe367b0be...,"Dört basamaklı, rakamları birbirinden ve sıfır...","Bu soruyu çözmek için, verilen koşulları adım ...",Bu problemi adım adım çözelim:\n\n1) ABCD - DC...,model_a,gpt-4-0125-preview,claude-3-5-sonnet-20240620,Turkish,False,False,False,False,"[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",Dört basamaklı rakamları birbirinden ve sıfırd...,31,[Dört basamaklı rakamları birbirinden ve sıfır...,{'Turkish': 5},{'Turkish': 1.0}
3,00072026c68f5418ef2da238394e418ce72a534b9b22d5...,"현재 추천된 탑 3 종목인 Cabaletta Bio (CABA), Rocket Ph...","죄송하지만 저는 금융 조언을 제공할 수 없습니다. 저는 AI 모델이며, 투자 결정에...",현재 추천된 탑 3 종목에 순위를 매기기 위해서는 여러 가지 요소들을 고려해야 합니...,model_b,gemma-2-2b-it,llama-3.1-nemotron-70b-instruct,English,False,False,False,False,"[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",현재 추천된 탑 3 종목인 Cabaletta Bio (CABA) Rocket Pha...,15,"[현재 추천된 탑 3 종목인 Cabaletta, Bio (CABA) Rocket P...","{'Korean': 1, 'English': 1}","{'Korean': 0.5, 'English': 0.5}"
4,0007ce7cf6bc1b5a8f8a4669b854fb12030863c970d9dc...,Please be boring,"Alright, I'll be as boring as possible.\n\nTod...","Understood. Here is a straightforward, unadorn...",model_a,reka-flash-20240722,grok-2-2024-08-13,English,False,False,False,False,"[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",Please be boring,3,[Please be boring],{'English': 1},{'English': 1.0}

In [11]:
# load pickle file here ------X---------

In [21]:
# import pickle

# path = '/kaggle/input/dom-data/dom_pickle'

# try:
#     with open(path, 'rb') as f:
#         df = pickle.load(f)
#     print("Pickle file loaded successfully!")
# except Exception as e:
#     print(f"Error loading pickle file: {e}")

Pickle file loaded successfully!

In [39]:
# later : just check when dictionary have languages with equal ratio then care 

def get_dom_language(row):
    counter = row['prompt_counter']
    if counter:
        max_pair = max(counter.items(), key=lambda x: (x[1], x[0] == "english"))
        return max_pair[0]
    else:
        print(counter,' : ',row['id'],' : ',row.index[0])

In [40]:
tqdm.pandas()
df['dom_lang'] = df.progress_apply(get_dom_language, axis=1)

 51%|█████     | 24538/48439 [00:00<00:00, 126544.34it/s]

{}  :  01614dda88361a6c798c8e7c98f3bcaef620952b2f5e937712f5a5bcd2a0e673  :  id
{}  :  03e57995fca216a372b3d8722fc0726f182f6ccf15635b5cea9e3aad2c2658ce  :  id
{}  :  0c771722678945793a14015e5f562d8c027c3bb0a844a1fba9852e66c96b2d67  :  id
{}  :  0cb443e2567ad409963c23da63a7187525460bfc9992f089337a3fed29f3d4a9  :  id
{}  :  0ee2f2b81d501a253bc2bb5ceb95d976714a86511732987c3ca82e5dbe614dbe  :  id
{}  :  100c380f1b5487e8ada5960a00e5ba37c259482b542e15e5d3e13aabe08bb8b5  :  id
{}  :  10dbae7b441799bdffdc44580cf20fa6a56b59aef5e68c00f0b70d88e1bbf6a5  :  id
{}  :  1126b35fc8bd99fc6bd7dca3d544de2f36a24a4b4f143f2e2c3da6b2a7d9e637  :  id
{}  :  12aa7402d588ed91a6a7ee273de258501413c464e6e3176db8776bebce7ded11  :  id
{}  :  1339b68bb10f0c530673284c42654c22154a4200deecb58ab857bf0c3d08a847  :  id
{}  :  145ba6104ed58c0a7b35d95cdf8ad3b26ab7ec7ea5aa088623cbdc91316d710e  :  id
{}  :  1aea39cd4b4d24a73646739bd08359d172bac3c92cd3c45bc6fe9653c8a67535  :  id
{}  :  1b3ec9f4b9b505c106c02e00b90fa086b63c83f0f6bf9b241127e8af2295255c  :  id
{}  :  1f2b5a190580ac7cc5e7c248e2fad894d09f8f25d45056e65634f2bb3b3fdf03  :  id
{}  :  227ea5b51e751ddecb75cc4835c228cb99ed594880f4dbdbfdc24846ae90b9d9  :  id
{}  :  2851a946925b42d7526fab4fae8e59bf9628f6369d4802ff4e747a133cb4d56a  :  id
{}  :  2c574c37223d87be088b7b4edcce4336b35ede3da06c23785639ee7eb58adb73  :  id
{}  :  3682980e0d8c9ec63c098ff3d4584b451358048dcbb0ce55e4da85c2b2ae56c5  :  id
{}  :  3a0206621f270450da1c005f476064071a95cdbb923e551f6e6cec045332406e  :  id
{}  :  3c222bd4fed24616eacb97f475aada62b8bfa0cb433e5f9fe9924409dc5eb762  :  id
{}  :  3cd954cbf7363e2ec135a81e1efa60e5050d5cef49e2a9d5a383561dd3da36d0  :  id
{}  :  427d5f07ceb7092add62a3b7f4dae04340430d147d578957324904455013a30e  :  id
{}  :  43daf03fb6024aa28da3c04bd9661576c8329041b5ea73e906e329e03e5b34bb  :  id
{}  :  47b4c6036c53915bcb090902724bf1b991cd0ccae60ccbb2b76c65bdf3d724b3  :  id
{}  :  488252ae9447b20d32b98102c695d96f1dbd8764c14f2648e33508aaae05af00  :  id
{}  :  4bd2eeda300ab71b653eed2b14d58cbba143f29e9561934497cd786de5af3af0  :  id
{}  :  4c5aaeef1f43f142891745940b93ac4b7acf29969055869ea28e6f13eedf29cd  :  id
{}  :  57d0cb00cb74bad619f01e235b46ae8d94b83b5d021cefbc2f462c9e2f5d37ee  :  id
{}  :  5b251c1a5bf3d4515d8cdc859f308555e34e35ec1c767a8e7f533688ceea02a3  :  id
{}  :  5c9006dbea5202584cbc6440049602cff18cee8591289a3836ad1f7672a9d750  :  id
{}  :  5c99f159d1615536891d8586dab9bcc8dff2a1fbb136db8fabe09af90c0e8c4c  :  id
{}  :  5dec2f712bd23c04e2fac1f0eb232ce7e0ba584e6bb5d2c929c69b60a8adda3a  :  id
{}  :  5ef93bd786342fa1eca9eccf558a21e64b3eea38a97c0e53cd1b4cded782458e  :  id
{}  :  6156e4b9e28ee709d2617f91b74a3c57707ac493f1b2e3f9767b42d5fbace405  :  id
{}  :  61edf8da62bc67bfc631406ff99843eba93595f0661fec10a0859c4c900b4dfc  :  id
{}  :  69db4120a9675fbb06ddea9fe9aeca5a3b17534bfc940d98057fb860b47c0f4b  :  id
{}  :  73e21ed1dd488e615af9f3b3ecc15472c4fb8da8cff95240255151c4dbe3ff99  :  id
{}  :  77994390e5df247379fad986167145bd17fc0f5f1db9d5a5c5a8dec4dc5eea3b  :  id
{}  :  7a2b542c518df0d95ffe17de3b7d966adf960822536e073739ca1c417f42f389  :  id
{}  :  7c397cdd73360e486e475baeab5a30a33518e3af377a3123c8261152c1751177  :  id
{}  :  7dcf37938910d09a0cbbcc5a12affad0ff9f4e6e187774a6ae801b1002ceb7e7  :  id
{}  :  7e2e154e968f8538b578808c3de0e79e642881b9308381f47bb73cb276a6d4df  :  id
{}  :  7fc46f98bb4036cabd85e67a4f829a4cd040cf4d49c544399cfad96891fec0cb  :  id
{}  :  8200d5970ab16b2632d275788d3ac403fbfe1516be22da1c3c255ea5c7f03ded  :  id
{}  :  85ffa8305f6bb1b1a5d003b5197422232fd73a24b3dfa7b3828388dabbc1e2c6  :  id
{}  :  87e73322a3cfda4493bd7f98f883437290897fdf2000c4a77428bdde18601f6a  :  id
{}  :  8db964b5e124535e9ba1a2aaf74925b07aadc893fa5588ff5933b044e78fbd3e  :  id
{}  :  90b7c8d2af91eaabd77f93709f4c4eb07bcf5fe4886e351a92420a67544cf4a8  :  id
{}  :  92364c8e4f687a396e7d14e916e8ce64a4946ea4abb73e8cb6500a1793ba7927  :  id
{}  :  93a8b24c64dc2d7dca6078ea68e9c8d1141033578b4fff99824ad79ef1722c85  :  id
{}  :  990ce4e163c083ab9ba55b2e598ff4dca9ea1e20501296bcc72ef99da22cb796  :  id
{}  :  9bb198b188e273b5ed4055832904d592e9ba1b1f7a46d07abd6881809ac78a26  :  id

100%|██████████| 48439/48439 [00:00<00:00, 119471.24it/s]

{}  :  9d5b344b55a8051aeeb6ef564a28057305d55e479455ac688029725c8af5ac9a  :  id
{}  :  9e435e1418125bad160b40ba6ad66e0241e56617647572e088bbca63281c34a6  :  id
{}  :  9e53496d3f1ff2e98151885add7fb857d14d0908d122e53b518f35bb97895d64  :  id
{}  :  9f61f90a3d2903cbbc95cd73b211b44ce648742f57396668efef5cfe2e4f90f1  :  id
{}  :  a12daf251c7ceaebc9da2089324f7564452ed326b201f233f918314bfbd2d659  :  id
{}  :  a9be5bc2ebf7290ddbb533050a3bc7fafff322009da0b773bc3b0256407f8638  :  id
{}  :  ab094108cf53ecf87ee0bec2542b3c9487d60e2affa109b3a8b19c2656b86c2f  :  id
{}  :  ab90c714f0a927ee2a1b4206f1bf8fea714f49a6b80ee2ed2d80360b11ed9fec  :  id
{}  :  b08069dd3c7c2b34e07f996fd3b42f503b1c1f527d908319fb36c3e3bbade3c0  :  id
{}  :  b0be6944c2f814091aa702af34e9e9dd757ac119409e99260611573f33f3ba75  :  id
{}  :  b1b424b5961e13a834091cb5e7b8f77282a3828cf1fdeb31268f8ac7668b9539  :  id
{}  :  b252d898aca4da84915f558d0fc9d906b38d7da28b23104c165110f420b25ca6  :  id
{}  :  b43b32b4be2894b90a4a7b9e96980b41de56fbe6da211e721f15a8512527f0bb  :  id
{}  :  b4b5d3cbec5166b7a37ba390f3215c6842c90bade5f0f04952abe725452de8bd  :  id
{}  :  b63122dabc0457a9c5f75541790f8627ba39b70c76922927c73697b6eef71866  :  id
{}  :  b889d24644ac18e24801d705b85cc90c9ed30cb1fa40d4a0f5c35dd8c74563bd  :  id
{}  :  bc25cc96111e53dfc30de0ad84166d04754684d07c2bf8f0490066234ef68a06  :  id
{}  :  bdd5ca89f659a085f0124fdda35f01e84c7eb7575d50a34dd71d1bbf2c88b101  :  id
{}  :  c0a9b44e92fa7791d045fb07c5f06407572dc9e517e2b0e45570935fd4062ca8  :  id
{}  :  c567324865c5767afb72c96f63445f653676f60fc640de10618eb64149c811b5  :  id
{}  :  c5c755a5bf9adf71215504a75e7e05ba2a8ee644d7c991b82c153743c8427c2d  :  id
{}  :  cb977f71749218f16423f69b9b1d133b303f1ed999f27a504bce2ed7ef6e31f1  :  id
{}  :  d12d44457b97eafde5d2affeb2aa72fa405cabc3493fdddbd648279b3ddcb6f3  :  id
{}  :  d30598291af2d951e5713858fe3dfb5ba1d7dbbf06770b1ca3760997ff948b03  :  id
{}  :  d74720ee8d30880459d42ef7b36f9e30cbf2e409986fd9b88a187e10161a9e14  :  id
{}  :  d7919663b1f94f4c5ad6d1928f9bc5fb55b45fee325c8da96ce3f6d538405e41  :  id
{}  :  d7f3b78249c8c32456887ba3fd15b9878e82b998c77466c3aee58d5557748ce2  :  id
{}  :  d8c56d0cafcbadb76cebd7e350396d03c0e8a4bb18d5112ee0c195a96b2b9d48  :  id
{}  :  d926a8894f5941b90a4113e9745a50c493cf22cc2e04c0aa7855033fa90bd62f  :  id
{}  :  d928815b7d244172edb91a65d0d1aa6cdd2cb0ca58b9f2c3b97b8457d1549b06  :  id
{}  :  d9bfcc7155822310eeeb5a46d4a6452a8feb1a6be1f23ed3622f476b8d9e1483  :  id
{}  :  da124480bf4c279249a6b03d3877b9698faa802d47994fd2f29753ec937f9cb4  :  id
{}  :  db76d177d27b4769575d459ca4771c318f49f05f69075e6dbe1a03dd432686a6  :  id
{}  :  dce48443d3a1522b6b71c47cbeeff17f6e09d2d714619139d371e3d8203ff758  :  id
{}  :  ded27fe1ab6f2b464ebf8fe819e6b2a9efec491d775ea316172ac7fdf276f175  :  id
{}  :  e50b16f992786e5b4e550808d717b999ab3da072397e8ad9d5ed7efa83d92ffb  :  id
{}  :  eeddfd3efa9857b9f537cd41999e09a92cba9d54dd5bd0e3f5e43046e9aef4b5  :  id
{}  :  efb264cff8b8d35d300dfa4847e1d412d0f1308a8a721f300492a199829d65ee  :  id
{}  :  f006ae6c3f8e53ec38f42bd517ad489593fadb39dc4dfe92fc85de772d4291aa  :  id
{}  :  f08fb69d49a38f6e81a95a7f38bf5ff7b14fb2c455e989ac8d84624f41e1e52b  :  id
{}  :  f1edaafbc557db0c4b01dbc74e88844a28434725ce2e193754e3f2821e3a25c2  :  id
{}  :  f4fe626c3e1ddc5d9ba1d65944a7f8ae8f9ecb9dac0a608d0eb713f339e6a89c  :  id
{}  :  f58b3b9bb79a8c54f955d0fce7c58997550f91428ad66fe3abc441f6fa382172  :  id
{}  :  f5cbaeab784cd4b7c54d0d3d72c0c80fe326ae3fc017a7d4732d55e2e35f69fc  :  id
{}  :  f685518446b7d1ac734796459f9d44d2b2b43940ac24defab4094abfeaad2085  :  id
{}  :  f692bfeaae40f1a2ebb037c338471ef52aa4acba570785b90b61d5818350bcd0  :  id
{}  :  f97f8f87eb760306169fc97c013053c60c29ad6cf39604b1fb5513c4f2bb1303  :  id
{}  :  f9a1dcdef26d71ade940ac8cf3f47bebb6e873d296f5dad3aba3723e9dee8a6c  :  id
{}  :  fa8494fddeca0fce8ea9d6be9c2c8bd91683c6ab747f7040f8bbb0377794d434  :  id
{}  :  fe384348a719c1ad83966a51ed60aa26212c132e46aeaf83ba3463aaa6331a26  :  id

### Final categorization

In [41]:
def contains_mathematical_operations(text, threshold=0.3):
    numbers = re.findall(r'\d+(\.\d+)?', text)
    operators = re.findall(r'[+\-*/=]', text)
    equation_pattern = r'(\d+=)+\d+'
    equations = re.findall(equation_pattern, text)
    math_expression_pattern = r'(\d+[+\-*/=]\d+)'
    math_expressions = re.findall(math_expression_pattern, text)
    total_chars = len(text)
    try:
        num_chars = sum(len(num) for num in numbers)
        if total_chars<=0:
            return False
        proportion_of_numbers = num_chars / total_chars
        if proportion_of_numbers > threshold or len(equations) > 0 or len(math_expressions) > 0:
            return True
        else:
            return False
    except:
        print(text)

In [42]:
def text_code_unknown_categorization(row):
    if row['code']:
        return 'code'
    if contains_mathematical_operations(row['ft_prompt']) or contains_mathematical_operations(row['response_a']) or contains_mathematical_operations(row['response_b']):
        return 'logical_operation'
    counter = row['prompt_counter']
    if counter:
        return 'text'
    else:
        return 'unknown'

In [43]:
tqdm.pandas()
df['type'] = df.progress_apply(text_code_unknown_categorization, axis=1)

100%|██████████| 48439/48439 [00:15<00:00, 3030.70it/s]

### Translation to dominating language

In [44]:
!pip install googletrans==4.0.0-rc1

Collecting googletrans==4.0.0-rc1
  Downloading googletrans-4.0.0rc1.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Downloading httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.8.30)
Collecting hstspreload (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hstspreload-2025.1.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h2-3.2.0-py2.py3-none-any.whl.metadata (32 kB)
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl.metadata (7.2 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hpack-3.0.0-py2.py3-none-any.whl.metadata (7.0 kB)
Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 3.3 MB/s eta 0:00:00
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 5.5 MB/s eta 0:00:00
Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.6 MB/s eta 0:00:00
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 3.6 MB/s eta 0:00:00
Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 4.3 MB/s eta 0:00:00
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Downloading hstspreload-2025.1.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.3 MB/s eta 0:00:0000:01
Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 2.9 MB/s eta 0:00:00
Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17397 sha256=e95dc7f88a1baa3d2ecab89c475d3921cc718dc7f96d30398f1cccda2d98beb8
  Stored in directory: /root/.cache/pip/wheels/c0/59/9f/7372f0cf70160fe61b528532e1a7c8498c4becd6bcffb022de
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
Successfully installed chardet-3.0.4 googletrans-4.0.0rc1 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2025.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0

In [45]:
from googletrans import Translator, LANGUAGES

translator = Translator()

In [46]:
def translation(row):
        
    source_language = "auto"
    target_language = row['dom_lang']  
    if target_language=='None' or target_language==None:
        target_language='english'
        
    response_a = row['response_a']
    response_b = row['response_b']
    prompt = row['ft_prompt']
    
    if row['type']=='unknown' or row['type']=='code' or row['type']=='logical_operation':
        return prompt,response_a,response_b
  
    src_code = next((code for code, name in LANGUAGES.items() if name.lower() == source_language.lower()), None)
    dest_code = next((code for code, name in LANGUAGES.items() if name.lower() == target_language.lower()), None)
    
    if src_code and dest_code:
        tr_prompt = translator.translate(prompt, src=src_code, dest=dest_code)
        tr_response_a = translator.translate(response_a, src=src_code, dest=dest_code)
        tr_response_b= translator.translate(response_b, src=src_code, dest=dest_code)
        return tr_prompt.text,tr_response_a.text,tr_response_b.text
    else:
        return prompt,response_a,response_b

In [47]:
tqdm.pandas()
tr_list = list(df.progress_apply(translation, axis=1))

100%|██████████| 48439/48439 [00:01<00:00, 26157.66it/s]

In [48]:
df['tr_meta'] = tr_list
df['tr_prompt']= df['tr_meta'].apply(lambda x: x[0])
df['tr_response_a']= df['tr_meta'].apply(lambda x: x[1])
df['tr_response_b']= df['tr_meta'].apply(lambda x: x[2])
del(df['tr_meta'])

### Weighted sum calculation for both the responses

In [49]:
!pip install polyglot
!pip install PyICU
!pip install pycld2

Collecting polyglot
  Downloading polyglot-16.7.4.tar.gz (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 3.2 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: polyglot
  Building wheel for polyglot (setup.py) ... done
  Created wheel for polyglot: filename=polyglot-16.7.4-py2.py3-none-any.whl size=52561 sha256=ac99da9e580e375e99cf5a41ff839e1e717c6361fe180f5919f5cc29705f9ed1
  Stored in directory: /root/.cache/pip/wheels/aa/92/4a/b172589446ba537db3bdb9a1f2204f27fe71217981c14ac368
Successfully built polyglot
Installing collected packages: polyglot
Successfully installed polyglot-16.7.4
Collecting PyICU
  Downloading PyICU-2.14.tar.gz (263 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.9/263.9 kB 5.8 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PyICU
  Building wheel for PyICU (pyproject.toml) ... done
  Created wheel for PyICU: filename=PyICU-2.14-cp310-cp310-linux_x86_64.whl size=1809836 sha256=3c6e145ac7bc752ad02661ab81e627795a13f9f00c56dc9d4955bb843d0578ef
  Stored in directory: /root/.cache/pip/wheels/78/6e/76/17c73021179c06c29d9b108896b9248da0de4f2af93f63d405
Successfully built PyICU
Installing collected packages: PyICU
Successfully installed PyICU-2.14
Collecting pycld2
  Downloading pycld2-0.41.tar.gz (41.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 MB 40.9 MB/s eta 0:00:00:00:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycld2
  Building wheel for pycld2 (setup.py) ... done
  Created wheel for pycld2: filename=pycld2-0.41-cp310-cp310-linux_x86_64.whl size=9904072 sha256=a8e073fae0dbbc0d91262c238dd39bc4aed9dd21b4cb8546bdb1a6fd903e20cc
  Stored in directory: /root/.cache/pip/wheels/be/81/31/240c89c845e008a93d98542325270007de595bfd356eb0b06c
Successfully built pycld2
Installing collected packages: pycld2
Successfully installed pycld2-0.41

In [50]:
def clean_before_wt_sum(text):    
    characters_to_remove = r"[-.,\n'\":!?]"
    cleaned_text = re.sub(characters_to_remove, "", text)
    final_text = re.sub(r"\s+", " ", cleaned_text).strip()
    return final_text

In [58]:
from polyglot.detect import Detector
from charset_normalizer import from_bytes

def club_detection(row):
    
    if row['type']=='unknown' or row['type']=='logical_operation':
        return -1,-1,{},{}
    
    response_a_language_frequency={}
    response_b_language_frequency={}
    response_a_weighted_sum=0
    response_b_weighted_sum=0
      
    set_weight = row['prompt_weight']
    response_a = clean_before_wt_sum(row['response_a'])
    response_b = clean_before_wt_sum(row['response_b'])
    
    try:
        response_a_detector = Detector(response_a, quiet=True)
        response_b_detector = Detector(response_b, quiet=True)
        
        for language in response_a_detector.languages:
            if language.read_bytes==0 or language.name=='un':
                proportion=0
            else:
                proportion = language.read_bytes / sum(lang.read_bytes for lang in response_a_detector.languages)
            if (language.name not in response_a_language_frequency) and language.name!='un':
                response_a_language_frequency[language.name]=proportion
    
        for language in response_b_detector.languages:
            if language.read_bytes==0 or language.name=='un':
                proportion=0
            else:
                proportion = language.read_bytes / sum(lang.read_bytes for lang in response_b_detector.languages)
            if (language.name not in response_b_language_frequency) and language.name!='un':
                response_b_language_frequency[language.name]=proportion
    
        for key in list(response_a_language_frequency.keys()):
            if key in list(set_weight.keys()):
                response_a_weighted_sum = response_a_weighted_sum + set_weight[key]*response_a_language_frequency[key]
            else:
                response_a_weighted_sum = response_a_weighted_sum + 0*response_a_language_frequency[key]
    
        for key in list(response_b_language_frequency.keys()):
            if key in list(set_weight.keys()):
                response_b_weighted_sum = response_b_weighted_sum + set_weight[key]*response_b_language_frequency[key]
            else:
                response_b_weighted_sum = response_b_weighted_sum + 0*response_b_language_frequency[key]

    except:
        print(row['id'])
        # print(response_b_detector)

    return response_a_weighted_sum,response_b_weighted_sum,response_a_language_frequency,response_b_language_frequency

In [59]:
tqdm.pandas()
wt_list = list(df.progress_apply(club_detection, axis=1))

  1%|          | 263/48439 [00:00<00:34, 1378.35it/s]

0146c7de6e50ec02d9ccf81a68fb9f576cb128d8e259769fd40fc11be72fd842

  9%|▉         | 4467/48439 [00:02<00:25, 1704.25it/s]

16495abe725138b61e2461a3e4cc35a0ed4eaaf393f1e2b1795f78e988d5fdb7

 14%|█▎        | 6626/48439 [00:04<00:23, 1754.20it/s]

2122e0b589c878a9fad3c522ec911f4570615fd10f28ede535399f062dd63f8c

 14%|█▍        | 6980/48439 [00:04<00:23, 1747.31it/s]

22e9d4c45fc6bd66dd49ebbf7a21ba43f47402f3e15d7e046fed051c80d5b1ed
2341d92bf76ce2d720ff0708a5a45567785f64262054c3cca7fc496dd959a6d5

 22%|██▏       | 10517/48439 [00:06<00:22, 1660.33it/s]

362a5ee94773e5d3745decde892ed2ca407a1041f998eaec81b6da806deb2f80

 26%|██▋       | 12828/48439 [00:07<00:20, 1772.14it/s]

42330d84fa4b1f5cf30afa4955f1ad2edb965982a9a65bac5164c66eb3eccb50

 30%|███       | 14606/48439 [00:08<00:19, 1721.63it/s]

4c12e1f8d424019a4fba1c5105158afe2dab5b2833c76507e2ad1c7961a8eab2

 33%|███▎      | 16015/48439 [00:09<00:18, 1735.20it/s]

534ce2fe2214cbedd7fba50c423f2cf195ca68b2b626df78c9bbd1ad20a7a9f4

 37%|███▋      | 17752/48439 [00:10<00:17, 1741.95it/s]

5cd1b910fc64de91060810a103baffa9e62ff7aeba886003194f52560907a64f

 50%|████▉     | 24032/48439 [00:14<00:13, 1820.96it/s]

7d4b3c63f0333f5ac45641df5afa770ddcc97934fb819ee05134be5ca5e124b0
7e6bb23a3cb246dd436117602553128742215b9cf5fa20372c56f0d42ae74ef3

 54%|█████▍    | 26318/48439 [00:15<00:13, 1663.99it/s]

8969a0c769d458cc58a79bb7a91adae2e00cf5f766450d3a47f8a2a6de1f207a
8a1f86f6ece1966c002c02b35c41984854e18109dd6c087fcdf68c5149ba07c0

 57%|█████▋    | 27551/48439 [00:16<00:11, 1752.86it/s]

8fd3708cdc2f6509ee60add5ce4280fe8f3cbf8f20e6dd4b871776e7030dbc6b

 58%|█████▊    | 27915/48439 [00:16<00:11, 1746.11it/s]

91bb4884ec182eec2bd2358853a2cf1feabaececdf87e8c4dc919421de4e1023

 59%|█████▊    | 28453/48439 [00:16<00:11, 1756.20it/s]

94998771ba1e853cedccc1ba0af699add8b331814f1c42822768931d1abf466e
959cbb46e1df8ee8db91bd43873091029a420c9c0665123b3324820e62afc314

 69%|██████▉   | 33471/48439 [00:19<00:08, 1722.50it/s]

afcd6cbe29bcf6fba19f05719a80076c62481d3b5d167f31415e1cf062b16c49

 70%|██████▉   | 33811/48439 [00:20<00:09, 1604.18it/s]

b1a2b39bdfc22cf135f7b686c12c3e4bc86eb7b80ceed4936a692377c7d857e4

 88%|████████▊ | 42425/48439 [00:25<00:03, 1631.50it/s]

df0d6ea8667bbaa31daab6a4b1990445cdd83f9eb8cff90356c8eeb013062f26
e0b65f52bc05f229a9dbb8f07820c0e251b1b0fd2c77492cfce969f62ea34453

 94%|█████████▎| 45372/48439 [00:26<00:01, 1744.51it/s]

ee53cda861b9e22a7e1d06473bc9f334bd98de111fd3a0cf96cba0181d58b897
ef538231819cb5c37f90f4a14e392c0be4f0f427f9154e813c1f4f3a260e9c47

100%|██████████| 48439/48439 [00:28<00:00, 1685.64it/s]

fecd4f4c62c0d4c47b7eca485a1e3b2811d59cef3d2957bee94a2399dabc4d5a

In [60]:
df['wt_meta'] = wt_list
df['wt_sum_response_a']= df['wt_meta'].apply(lambda x: x[0])
df['wt_sum_response_b']= df['wt_meta'].apply(lambda x: x[1])
df['counter_response_a']= df['wt_meta'].apply(lambda x: x[2])
df['counter_response_b']= df['wt_meta'].apply(lambda x: x[3])
del(df['wt_meta'])

In [61]:
len(df[df['type']=='text']) , len(df[df['type']=='code']) , len(df[df['type']=='logical_operation']) , len(df[df['type']=='unknown'])

(32092, 12082, 4214, 51)

In [6]:
# df.to_pickle("pixel_part_two")

### Similarity Score

In [64]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# from transformers import AutoTokenizer, AutoModel
# import torch

In [65]:
# model_name = "sentence-transformers/all-MiniLM-L6-v2"
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModel.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

In [11]:
# def embed_text(text):
#     tokens = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
#     with torch.no_grad():
#         embeddings = model(**tokens).pooler_output
#     return embeddings


# def deep_similarity(text1,text2,detected_language='english'):
#     embeddings1 = embed_text(text1)
#     embeddings2 = embed_text(text2)
    
#     cosine_similarity = torch.nn.functional.cosine_similarity(embeddings1, embeddings2)
#     return cosine_similarity.item()


# def similarity_score(row):
#     if row['type']=='logical_operations' or row['type']=='unknown':
#         return -1,-1
#     prompt = row['prompt']
#     response_a = row['response_a']
#     response_b = row['response_b']
#     language = row['language']
    
#     response_a_similarity_score = deep_similarity(prompt,response_a,language)
#     response_b_similarity_score = deep_similarity(prompt,response_b,language)

#     return response_a_similarity_score,response_b_similarity_score

In [ ]:
# tqdm.pandas()
# sm_list = list(df.progress_apply(similarity_score, axis=1))

 85%|████████▌ | 41180/48439 [1:29:33<17:25,  6.94it/s]

In [66]:
!pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.44.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.4.1+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.24.7)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.19.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 5.6 MB/s eta 0:00:0000:01
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.3.1

In [67]:
import logging
from sentence_transformers import SentenceTransformer, util

# Suppress unnecessary output
logging.getLogger("transformers").setLevel(logging.WARNING)
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)

# Load a pre-trained multilingual model
model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
model = SentenceTransformer(model_name)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.12k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [68]:
def compute_similarity(row):

    if row['type']=='logical_operations' or row['type']=='unknown':
        return -1,-1
        
    prompt = row['tr_prompt']
    response_a = row['tr_response_a']
    response_b = row['tr_response_b']

    prompt_embeddings = model.encode(prompt, convert_to_tensor=True)
    response_a_embeddings = model.encode(response_a, convert_to_tensor=True)
    response_b_embeddings = model.encode(response_b, convert_to_tensor=True)
    
    response_a_similarity_score = util.pytorch_cos_sim(prompt_embeddings, response_a_embeddings)
    response_b_similarity_score = util.pytorch_cos_sim(prompt_embeddings, response_b_embeddings)
    
    return response_a_similarity_score.item(), response_b_similarity_score.item()

In [69]:
tqdm.pandas()
sm_list = list(df.progress_apply(compute_similarity, axis=1))

100%|██████████| 48439/48439 [30:51<00:00, 26.16it/s]

In [70]:
df['sm_list'] = sm_list
df['similarity_score_response_a']= df['sm_list'].apply(lambda x: x[0])
df['similarity_score_response_b']= df['sm_list'].apply(lambda x: x[1])
del(df['sm_list'])

In [15]:
# df.to_pickle('pixel_part_three')

### Vocab Complexity

In [71]:
import re

def calculate_vocabulary(text):

    tokens = re.findall(r'\w+', text, re.UNICODE)
    normalized_tokens = [token.lower() for token in tokens]
    unique_words = list(set(normalized_tokens))
    return len(unique_words)


def vocab_complexity(row):
    if row['type']=='logical_operation' or row['type']=='unknown':
        return -1,-1,-1
        
    tr_prompt = row['tr_prompt']
    tr_response_a = row['tr_response_a']
    tr_response_b = row['tr_response_b']

    prompt_score=0
    response_a_score=0
    response_b_score=0
    
    if len(tr_prompt) != 0:
        prompt_score = round(calculate_vocabulary(tr_prompt)/len(tr_prompt),4)
    if len(tr_response_a)!=0:
        response_a_score = round(calculate_vocabulary(tr_response_a)/len(tr_response_a),4)
    if len(tr_response_b) != 0:
        response_b_score = round(calculate_vocabulary(tr_response_b)/len(tr_response_b),4)
    
    return prompt_score, response_a_score, response_b_score

In [72]:
tqdm.pandas()
vcs_list = list(df.progress_apply(vocab_complexity, axis=1))

100%|██████████| 48439/48439 [00:16<00:00, 2988.99it/s]

In [73]:
df['vcs_list'] = vcs_list
df['vocabulary_complexity_prompt']= df['vcs_list'].apply(lambda x: x[0])
df['vocabulary_complexity_response_a']= df['vcs_list'].apply(lambda x: x[1])
df['vocabulary_complexity_response_b']= df['vcs_list'].apply(lambda x: x[2])
del(df['vcs_list'])

In [75]:
# df.to_pickle('phaseOne_dataset')

### Categorical columns encoding

In [79]:
columns_to_transform = ['code_in_prompt','code_in_response_a','code_in_response_b']
df[columns_to_transform] = df[columns_to_transform].astype(int)

In [ ]:
df[["web_dev_prompt", "dev_prompt", "comprehensive_prompt"]] = pd.DataFrame(df["code_languages_in_prompt"].tolist(), index=df.index)
df[["web_dev_response_a", "dev_response_a", "comprehensive_response_a"]]= pd.DataFrame(df["code_languages_in_response_a"].tolist(), index=df.index)
df[["web_dev_response_b", "dev_response_b", "comprehensive_response_b"]] = pd.DataFrame(df["code_languages_in_response_b"].tolist(), index=df.index)

In [103]:
# label is winner column 

def target_conversion_to_categorical(model):
    if model == 'model_a':
        return 0
    else:
        return 1
        
df['label'] = df['winner'].apply(target_conversion_to_categorical)

In [120]:
dt = df[(df['type']=='code') | (df['type']=='text')]

In [123]:
len(dt[dt['type']=='unknown']) , len(dt[dt['type']=='logical_operations'])

(0, 0)

### final column selection for model training

In [124]:
dt.head(1)

,id,prompt,response_a,response_b,winner,model_a,model_b,language,code_in_prompt,code_in_response_a,code_in_response_b,code,code_languages_in_prompt,code_languages_in_response_a,code_languages_in_response_b,ft_prompt,prompt_len,prompt_segements,prompt_counter,prompt_weight,dom_lang,type,tr_prompt,tr_response_a,tr_response_b,wt_sum_response_a,wt_sum_response_b,counter_response_a,counter_response_b,similarity_score_response_a,similarity_score_response_b,vocabulary_complexity_prompt,vocabulary_complexity_response_a,vocabulary_complexity_response_b,web_dev_prompt,dev_prompt,comprehensive_prompt,web_dev_response_a,dev_response_a,comprehensive_response_a,web_dev_response_b,dev_response_b,comprehensive_response_b,label
0,00007cff95d7f7974642a785aca248b0f26e60d3312fac...,vieš po Slovensky?,"Áno, hovorím po slovensky. Ako vám môžem pomôcť?","Áno, veď som tu! Môžem ti pomôcť s otázkami al...",model_a,o1-preview,reka-core-20240904,Slovak,0,0,0,False,"[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",vieš po Slovensky,3,[vieš po Slovensky],{'Slovak': 1},{'Slovak': 1.0},Slovak,text,vieš po Slovensky,"Áno, hovorím po slovensky. Ako vám môžem pomôcť?","Áno, veď som tu! Môžem ti pomôcť s otázkami al...",1.0,0.585896,{'Slovak': 1.0},"{'English': 0.41410352588147037, 'Slovak': 0.5...",0.671602,0.134081,0.1765,0.1667,0.1495,0,0,0,0,0,0,0,0,0,0

In [125]:
# id removed

columns = ['label','code_in_prompt', 'code_in_response_a',
       'code_in_response_b', 'wt_sum_response_a', 'wt_sum_response_b',
       'similarity_score_response_a', 'similarity_score_response_b',
       'vocabulary_complexity_prompt', 'vocabulary_complexity_response_a',
       'vocabulary_complexity_response_b', 'web_dev_prompt', 'dev_prompt',
       'comprehensive_prompt', 'web_dev_response_a', 'dev_response_a',
       'comprehensive_response_a', 'web_dev_response_b', 'dev_response_b',
       'comprehensive_response_b']
dataset = dt[columns]

In [126]:
y = dataset['label']
X = dataset.drop(columns=["label"])

### Splitting dataset and training model

In [127]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

print("Training set size:", X_train.shape)
# print("Validation set size:", X_val.shape)
print("Test set size:", X_test.shape)

Training set size: (30921, 19)
Test set size: (13253, 19)

In [128]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(random_state=42)

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,  # 3-fold cross-validation
    scoring="accuracy",
    verbose=2,
    n_jobs=-1,  # Use all processors
)

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

print("Best Hyperparameters:", best_params)

y_test_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Validation Accuracy with Best Model:", test_accuracy)

Fitting 3 folds for each of 108 candidates, totalling 324 fits

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()

Best Hyperparameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 200}
Validation Accuracy with Best Model: 0.5597977816343469

In [129]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Initialize the Logistic Regression model
model = LogisticRegression(random_state=42, max_iter=1000)

# Define the hyperparameter grid
param_grid = {
    "penalty": ["l1", "l2", "elasticnet", "none"],
    "C": [0.01, 0.1, 1, 10, 100],  # Regularization strength
    "solver": ["saga"],  # 'saga' supports all penalty options
    "l1_ratio": [0.1, 0.5, 0.9],  # Only used if penalty is 'elasticnet'
}

# Set up the GridSearchCV
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,  # 3-fold cross-validation
    scoring="accuracy",
    verbose=2,
    n_jobs=-1,  # Use all processors
)

In [130]:
# Fit GridSearchCV on the training data
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 60 candidates, totalling 180 fits

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1165: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=none)
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(

GridSearchCV(cv=3, estimator=LogisticRegression(max_iter=1000, random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'l1_ratio': [0.1, 0.5, 0.9],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['saga']},
             scoring='accuracy', verbose=2)

In [131]:
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

print("Best Hyperparameters:", best_params)

y_test_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Validation Accuracy with Best Model:", test_accuracy)

Best Hyperparameters: {'C': 0.01, 'l1_ratio': 0.1, 'penalty': 'none', 'solver': 'saga'}
Validation Accuracy with Best Model: 0.556553233230212

### Code Comparision